name: recruitment_app
description: Ứng dụng tuyển dụng trực tuyến (Flutter + PHP + MySQL)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  dio: ^5.4.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  file_picker: ^8.1.2
  http_parser: ^4.0.2
  mime: ^1.0.5
  get_it: ^7.6.4
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  pdf: ^3.11.1
  printing: ^5.13.2
  path_provider: ^2.1.4
  intl: ^0.19.0
  permission_handler: ^11.3.1
  html_editor_enhanced: ^2.5.1
  flutter_html: ^3.0.0-beta.2
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.3
  flutter_markdown: ^0.7.3
  flutter_dotenv: ^5.1.0
  flutter_pdfview: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

